version: '3.8'

services:
  client:
    image: client:1.0.0
    restart: always
    environment:
      - ENVMODE=prod
    build:
      dockerfile: Dockerfile.prod
      context: ./client
    volumes:
      - './client:/app'
    ports:
      - '443:80'
    depends_on:
      - server
    networks:
      - shared-network

  server:
    image: server:1.0.0
    restart: always
    environment:
      - ENVMODE=prod
    build:
      dockerfile: Dockerfile.prod
      context: ./server
    volumes:
      - './server:/app'
    ports:
      - '8000:8000'
    networks:
      - shared-network
networks:
  shared-network:
